Add a means of skipping CI on Circle
This adds support for ci skip, skip ci, circle skip, and skip circle in
commit messages to avoid running the entire build and test suite. This
is akin to the skipping functionality provided by Travis and AppVeyor,
as well as Circle 1.0.

[ci skip]

diff --git a/circle.yml b/circle.yml
--- a/circle.yml
+++ b/circle.yml
@@ -24,6 +24,17 @@ jobs:
               sudo ln -s /usr/bin/$prog-4.8 /usr/local/bin/$prog;
             done
       - checkout # circle ci code checkout step
+      - run:
+          name: Check for a request to skip CI
+          command: |
+            msg="$(git rev-list --format=%B --max-count=1 $CIRCLE_SHA1)"
+            # [ci skip] was recognized in Circle 1.0 but not in 2.0
+            # Here we're also adding [circle skip], which is non-standard
+            if [[ $msg == *"[ci skip]"* ]] || [[ $msg == *"[skip ci]"* ]] || \
+               [[ $msg == *"[circle skip]"* ]] || [[ $msg == *"[skip circle]"* ]]; then
+              echo "User requested to skip CI, failing early"
+              exit 1
+            fi
 # (FIXME: need to unset url."ssh://git@github.com".insteadOf or libgit2 tests fail)
       - run:
           name: Checkout merge commit, set versioning info and Make.user variables
