Include checksum and remove hack

diff --git a/deps/tools/jlchecksum b/deps/tools/jlchecksum
--- a/deps/tools/jlchecksum
+++ b/deps/tools/jlchecksum
@@ -63,10 +63,10 @@ find_checksum()
         fi
     done
     if [ ! -f "$DEPSDIR/checksums/$BASENAME/$CHECKSUM_TYPE" ]; then
-        # if [ "${TAGGED_RELEASE_BANNER:-}" ]; then
-        #     echo "WARNING: $CHECKSUM_TYPE checksum for $BASENAME not found in deps/checksums/, failing release build." >&2
-        #     exit 3
-        # fi
+        if [ "${TAGGED_RELEASE_BANNER:-}" ]; then
+            echo "WARNING: $CHECKSUM_TYPE checksum for $BASENAME not found in deps/checksums/, failing release build." >&2
+            exit 3
+        fi
         echo "WARNING: $CHECKSUM_TYPE checksum for $BASENAME not found in deps/checksums/, autogenerating..." >&2
 
         # Generate as many checksum types as we can
